# Project information
site_name: Labs Engineering Standards
site_url: https://labs.lambdaschool.com/standards/
site_description: Engineering Standards for Lambda School Labs
site_author: Lambda School Labs

# Repository
repo_name: "Lambda-School-Labs/labs-engineering-standards"
repo_url: "https://github.com/Lambda-School-Labs/labs-engineering-standards"

# Copyright
copyright: © Lambda School

# Configuration
theme:
    name: "material"
    logo: images/Lambda_Shield_Red.png
    language: en

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - tables
    - admonition
    - codehilite
    - toc:
          permalink: true
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.inlinehilite

nav:
    - Home: standards/index.md
    - AWS: standards/topics/aws.md
    - Code Quality: standards/topics/code-quality.md
    - Data Persistence: standards/topics/data-persistence.md
    - Developer Workflow: standards/topics/developer-workflow.md
    - Git: standards/topics/git.md
    - GitHub: standards/topics/github.md
    - Heroku: standards/topics/heroku.md
    - Node.js: standards/topics/node-js.md
    - Programming Languages: standards/topics/programming-languages.md
    - React: standards/topics/react.md
    - Security: standards/topics/security.md
    - Third Party Services: standards/topics/third-party-services.md
    - Web API Frameworks: standards/topics/web-api-frameworks.md
    - Writing Standards: standards/topics/writing-standards.md
