name: Publish
on:
    push:
        branches:
            - master

jobs:
    publish:
        name: Publishing
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Checkout master
              uses: actions/checkout@v2

            - name: Install Python
              uses: actions/setup-python@v1.2.0
              with:
                  python-version: 3.7

            - name: Install pipenv
              uses: dschep/install-pipenv-action@v1

            - name: Install dependencies
              run: pipenv install

            - name: Build docs
              run: pipenv run mkdocs build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./site
                  cname: labs.lambdaschool.com
